### ISSUE TITLE
Regarding finding organisation to work with

### ISSUE THREAD

**Issue by Rajat2213** [taskflow/GSoC2022#1]
I want to know about any projects that are available right know. Please give me right direction to work on that particular project.
And Do you have any public mailing channel.

**Comment by Rajat2213** [comment]
Please reply I want to contribute.

**Comment by tsung-wei-huang** [comment]
Hi @Rajat2213 , thanks for your interest. Currently, we don't have any dedicated channels. But, you can always submit a meeting request [here](https://taskflow.github.io/#tag_contact) to schedule a meeting with the organizer. Thanks!
