### ISSUE TITLE
Channels to discuss the project 1

### ISSUE THREAD

**Issue by Weijun-H** [taskflow/GSoC2022#4]
Hi, I am really interested in this project 1 and have an initial idea about it. Could you tell me where I can discuss this, or do I have to request a meeting?

**Comment by tsung-wei-huang** [comment]
Hi @Weijun-H thanks for your interest! Please go ahead here: https://taskflow.github.io/#tag_contact and submit a request to schedule a zoom call.

**Comment by Weijun-H** [comment]
Thanks lot.
